import { GeoLayoutInstance as Geo } from "../../../../../engine/GeoLayout"

export const koopa_without_shell_geo = [
	{ command: Geo.node_shadow, args: [SHADOW_CIRCLE_4_VERTS, 0x9B, 100]},
	{ command: Geo.open_node },
	{ command: Geo.node_scale, args: [0x00, 16384]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600C498]},
	{ command: Geo.open_node },
	{ command: Geo.node_switch_case, args: [2, geo_switch_anim_state]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 114, 0, 0, koopa_seg6_dl_06007AF8]},
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 114, 0, 0, koopa_seg6_dl_06007B20]},
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, -29, 39, 60, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600B838]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 60, 0, 0, koopa_seg6_dl_060086D0]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, -29, 39, -60, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BA10]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 60, 0, 0, koopa_seg6_dl_06008B50]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 55, 25, -73, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BC18]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 54, 0, 0, koopa_seg6_dl_0600BA90]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 55, 25, 74, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BE10]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 54, 0, 0, koopa_seg6_dl_0600BC88]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_end },
]

export const koopa_with_shell_geo = [
	{ command: Geo.node_shadow, args: [SHADOW_CIRCLE_4_VERTS, 0x9B, 100]},
	{ command: Geo.open_node },
	{ command: Geo.node_scale, args: [0x00, 16384]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_06008250]},
	{ command: Geo.open_node },
	{ command: Geo.node_switch_case, args: [2, geo_switch_anim_state]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 114, 0, 0, koopa_seg6_dl_06007AF8]},
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 114, 0, 0, koopa_seg6_dl_06007B20]},
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, -29, 39, 60, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600B838]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 60, 0, 0, koopa_seg6_dl_060086D0]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, -29, 39, -60, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BA10]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 60, 0, 0, koopa_seg6_dl_06008B50]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 55, 25, -73, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BC18]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 54, 0, 0, koopa_seg6_dl_0600BA90]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 55, 25, 74, NULL]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 0, 0, 0, koopa_seg6_dl_0600BE10]},
	{ command: Geo.open_node },
	{ command: Geo.node_animated_part, args: [Geo.LAYER_OPAQUE, 54, 0, 0, koopa_seg6_dl_0600BC88]},
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.close_node },
	{ command: Geo.node_end },
]
